apiVersion: v1
kind: Pod
metadata:
    name: pod1
    labels: 
        app: prod
        env: xyz
    namespace: my-prod-server
spec:
    conatiners:
        - name: container1
        image: nginx
        ports:
            - name: http-port
            containerPort
