apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: prod
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetport: 80
  - name: http
    protocol: TCP
    port: 8080
    targetport: 8080