apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels: 
      app: prod
      env: xyz
  namespace: my-prod-server
spec:
  type: NodePort
  selector:
    app: pod1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http1
      protocol: TCP
      port: 8080
      targetPort: 8080